# -*- coding: utf-8 -*-
"""day2 Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WesqY-ykbMGhBjXnZ9WHV0cctdSjEQqP
"""

#1.Write a Python Program to Check Prime Number.
num = int(input("Enter a number: "))
# define a flag variable
flag = False
if num == 1:
    print(f"{num}, is not a prime number")
elif num > 1:
 # check for factors
    for i in range(2, num):
        if (num % i) == 0:
          flag = True # if factor is found, set flag to True
 # break out of loop
        break
 # check if flag is True
if flag:
 print(f"{num}, is not a prime number")
else:
 print(f"{num}, is a prime number")

#2.write a python program to find the sum of natural numbers,
number = int(input("enter the number"))
sum = 0
for i in range(1,number +1):
  sum = sum + i
print(f" sum of natural numbers is  {sum}")

#3. converting an integer into decimal
import decimal
integer = 10
print(decimal.Decimal(integer))
print(type(decimal.Decimal(integer)))

#4.converting a string of integers
import decimal
integer = '12345'
print(decimal.Decimal(integer))
print(type(decimal.Decimal(integer)))

#5.reversing a string using a extended string ,\
string = 'ajay krishna'
reverse_string = string[::-1]
print(reverse_string)

#6.Counting vowels in a given word
word = 'ajaykrishna'
vowel = ['a','e','i','o','u']
count = 0
for character in word:
  if character in vowel:
   count +=1
print(count)

#6.Counting consonants in a given word
word = 'ajaykrishna'
vowel = ['a','e','i','o','u']
count = 0
for character in word:
  if character not in vowel:
   count +=1
print(count)

#7.counting the number of occurances of a character in a string word = 'ajaykrishna'
word = 'ajaykrishna'
occurance = 0
for character in word:
  if character == 'a':
   occurance +=1
print(occurance)

#8.writing fibonacci series
fib = [0,1]
n = 5
for i in range(n):
  fib.append(fib[-1] + fib[-2])
print(','.join(str(e) for e in fib))

#9.finding the maximum number in a list
numlist = [33,22,44,55,66,77]
max = numlist[0]
for num in numlist:
  if max<num:
    max = num
print(max)

#10.finding the minimum number in a list
numlist = [33,22,44,55,66,77]
min = numlist[0]
for num in numlist:
  if min<num:
    max = num
print(min)

